// ACTION AUTH
export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_FAILURE = 'FETCH_AUTH_FAILURE';

// ACTION NOUS_SOMMES
export const FETCH_NOUS_SOMMES_REQUEST = 'FETCH_NOUS_SOMMES_REQUEST';
export const FETCH_NOUS_SOMMES_LIST_REQUEST = 'FETCH_NOUS_SOMMES_LIST_REQUEST';
export const PUT_UPDATE_STATE_NOUS_SOMMES_REQUEST = 'PUT_UPDATE_STATE_NOUS_SOMMES_REQUEST';
export const DELETE_NOUS_SOMMES_REQUEST = 'DELETE_NOUS_SOMMES_REQUEST';
export const POST_NOUS_SOMMES_REQUEST = 'POST_NOUS_SOMMES_REQUEST';
export const PUT_NOUS_SOMMES_REQUEST = 'PUT_NOUS_SOMMES_REQUEST';

export const FETCH_NOUS_SOMMES_SUCCESS = 'FETCH_NOUS_SOMMES_SUCCESS';
export const FETCH_NOUS_SOMMES_LIST_SUCCESS = 'FETCH_NOUS_SOMMES_LIST_SUCCESS';
export const FETCH_NOUS_SOMMES_FAILURE = 'FETCH_NOUS_SOMMES_FAILURE';

// ACTION NOS_SERVICES_ET_PRODUITS
export const FETCH_NOS_SERVICES_ET_PRODUITS_REQUEST = 'FETCH_NOS_SERVICES_ET_PRODUITS_REQUEST';
export const FETCH_NOS_SERVICES_ET_PRODUITS_LIST_REQUEST = 'FETCH_NOS_SERVICES_ET_PRODUITS_LIST_REQUEST';
export const PUT_UPDATE_STATE_NOS_SERVICES_ET_PRODUITS_REQUEST = 'PUT_UPDATE_STATE_NOS_SERVICES_ET_PRODUITS_REQUEST';
export const DELETE_NOS_SERVICES_ET_PRODUITS_REQUEST = 'DELETE_NOS_SERVICES_ET_PRODUITS_REQUEST';
export const POST_NOS_SERVICES_ET_PRODUITS_REQUEST = 'POST_NOS_SERVICES_ET_PRODUITS_REQUEST';
export const PUT_NOS_SERVICES_ET_PRODUITS_REQUEST = 'PUT_NOS_SERVICES_ET_PRODUITS_REQUEST';

export const FETCH_NOS_SERVICES_ET_PRODUITS_SUCCESS = 'FETCH_NOS_SERVICES_ET_PRODUITS_SUCCESS';
export const FETCH_NOS_SERVICES_ET_PRODUITS_LIST_SUCCESS = 'FETCH_NOS_SERVICES_ET_PRODUITS_LIST_SUCCESS';
export const FETCH_NOS_SERVICES_ET_PRODUITS_FAILURE = 'FETCH_NOS_SERVICES_ET_PRODUITS_FAILURE';

// ACTION INTRODUCTION_NOUS_REJOINDRE
export const FETCH_INTRODUCTION_NOUS_REJOINDRE_REQUEST = 'FETCH_INTRODUCTION_NOUS_REJOINDRE_REQUEST';
export const FETCH_INTRODUCTION_NOUS_REJOINDRE_LIST_REQUEST = 'FETCH_INTRODUCTION_NOUS_REJOINDRE_LIST_REQUEST';
export const PUT_UPDATE_STATE_INTRODUCTION_NOUS_REJOINDRE_REQUEST = 'PUT_UPDATE_STATE_INTRODUCTION_NOUS_REJOINDRE_REQUEST';
export const DELETE_INTRODUCTION_NOUS_REJOINDRE_REQUEST = 'DELETE_INTRODUCTION_NOUS_REJOINDRE_REQUEST';
export const POST_INTRODUCTION_NOUS_REJOINDRE_REQUEST = 'POST_INTRODUCTION_NOUS_REJOINDRE_REQUEST';
export const PUT_INTRODUCTION_NOUS_REJOINDRE_REQUEST = 'PUT_INTRODUCTION_NOUS_REJOINDRE_REQUEST';

export const FETCH_INTRODUCTION_NOUS_REJOINDRE_SUCCESS = 'FETCH_INTRODUCTION_NOUS_REJOINDRE_SUCCESS';
export const FETCH_INTRODUCTION_NOUS_REJOINDRE_LIST_SUCCESS = 'FETCH_INTRODUCTION_NOUS_REJOINDRE_LIST_SUCCESS';
export const FETCH_INTRODUCTION_NOUS_REJOINDRE_FAILURE = 'FETCH_INTRODUCTION_NOUS_REJOINDRE_FAILURE';

// ACTION POSTE
export const FETCH_POSTE_REQUEST = 'FETCH_POSTE_REQUEST';
export const FETCH_POSTE_APPLY_REQUEST = 'FETCH_POSTE_APPLY_REQUEST';
export const FETCH_POSTE_LIST_REQUEST = 'FETCH_POSTE_LIST_REQUEST';
export const PUT_UPDATE_STATE_POSTE_REQUEST = 'PUT_UPDATE_STATE_POSTE_REQUEST';
export const PUT_DUPLICATE_POSTE_REQUEST = 'PUT_DUPLICATE_POSTE_REQUEST';
export const DELETE_POSTE_REQUEST = 'DELETE_POSTE_REQUEST';
export const POST_POSTE_REQUEST = 'POST_POSTE_REQUEST';
export const PUT_POSTE_REQUEST = 'PUT_POSTE_REQUEST';

export const FETCH_POSTE_SUCCESS = 'FETCH_POSTE_SUCCESS';
export const FETCH_POSTE_LIST_SUCCESS = 'FETCH_POSTE_LIST_SUCCESS';
export const FETCH_POSTE_APPLY_SUCCESS = 'FETCH_POSTE_APPLY_SUCCESS';
export const FETCH_POSTE_FAILURE = 'FETCH_POSTE_FAILURE';
export const FETCH_POSTE_APPLY_FAILURE = 'FETCH_POSTE_APPLY_FAILURE';

// SLIDE TITLE
export const FETCH_SLIDE_TITLE_REQUEST = 'FETCH_SLIDE_TITLE_REQUEST';
export const PUT_SLIDE_TITLE_REQUEST = 'PUT_SLIDE_TITLE_REQUEST';

export const FETCH_SLIDE_TITLE_SUCCESS = 'FETCH_SLIDE_TITLE_SUCCESS';
export const FETCH_SLIDE_TITLE_FAILURE = 'FETCH_SLIDE_TITLE_FAILURE';

// ACTION SLIDE
export const FETCH_SLIDE_LIST_REQUEST = 'FETCH_SLIDE_LIST_REQUEST';
export const PUT_UPDATE_STATE_SLIDE_REQUEST = 'PUT_UPDATE_STATE_SLIDE_REQUEST';
export const DELETE_SLIDE_REQUEST = 'DELETE_SLIDE_REQUEST';
export const POST_SLIDE_REQUEST = 'POST_SLIDE_REQUEST';

export const FETCH_SLIDE_SUCCESS = 'FETCH_SLIDE_SUCCESS';
export const FETCH_SLIDE_LIST_SUCCESS = 'FETCH_SLIDE_LIST_SUCCESS';
export const FETCH_SLIDE_FAILURE = 'FETCH_SLIDE_FAILURE';

// CONTACTEZ_NOUS
export const FETCH_CONTACTEZ_NOUS_REQUEST = 'FETCH_CONTACTEZ_NOUS_REQUEST';
export const PUT_CONTACTEZ_NOUS_REQUEST = 'PUT_CONTACTEZ_NOUS_REQUEST';

export const FETCH_CONTACTEZ_NOUS_SUCCESS = 'FETCH_CONTACTEZ_NOUS_SUCCESS';
export const FETCH_CONTACTEZ_NOUS_FAILURE = 'FETCH_CONTACTEZ_NOUS_FAILURE';

// USER
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const PUT_UPDATE_EMAIL_USER_REQUEST = 'PUT_UPDATE_EMAIL_USER_REQUEST';
export const PUT_UPDATE_PASSWORD_USER_REQUEST = 'PUT_UPDATE_PASSWORD_USER_REQUEST';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

